baseURL = "https://guitarrapc.github.io/"
languageCode = "ja"
title = "guitarrapc on github"
theme = "hyde"
hasCJKLanguage = true
canonifyurls = true

[menu]
main = [
    { name = "Logs", urls = "/logs"},
]

[params]
themeColor = "theme-base-0d"
copyright = "guitarrapc"
description = "my resumes."