version: 2
jobs :
  deploy:
    docker:
      - image: jnyo/docker-hugo-firebase:latest
    working_directory: ~/project
    steps:
      - checkout
      - run:
          command: ./scripts/deploy.sh

workflows:
   version: 2
   build_and_deploy:
      jobs:
        - deploy:
            filters:
              branches:
                only: source
