version: 2.1
executors:
  default:
    docker:
      - image: jnyo/docker-hugo-firebase:latest
jobs :
  gitpush:
    executor: default
    working_directory: ~/project
    steps:
      - checkout
      - run: ./scripts/deploy.sh

workflows:
   version: 2
   push:
      jobs:
        - gitpush:
            filters:
              branches:
                only: source
